# Generated by Django 5.0.3 on 2024-03-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitorapp', '0003_alter_customuser_is_active'),
    ]

    operations = [
    ]
