# Generated by Django 5.0.3 on 2024-03-23 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('pulse_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pulse Rate (bpm)')),
                ('heart_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heart Rate (bpm)')),
                ('blood_oxygen_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Blood Oxygen Level (%)')),
                ('body_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Body Temperature (°C)')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)')),
                ('body_weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Body Weight (kg)')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
